
server:
  port: 8081

spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/order-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    # 重要！  开启消息发送确认机制
    publisher-confirms: true
logging:
  level:
    root: warn